[package]
name = "lem"
version = "0.1.0"
authors = ["deciduously <bendlovy@gmail.com>"]

[dependencies]
clippy = {version = "*", optional = true}
rocket = "0.1.4"
rocket_codegen = "0.1.4"

[features]
default = []
dev = ["clippy"]